version: "3.8"
services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root_user
      - MONGO_INITDB_ROOT_PASSWORD=root_pass
    command: --quiet
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      timeout: 10s

  cinema-ticket:
    depends_on:
      mongodb:
        condition: service_healthy
    container_name: cinema-ticket-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"


volumes:
  data: {}

networks:
  default:
    name: mongodb_network